name: Checks

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-setup

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Check Terraform files are properly formatted (run "terraform fmt -recursive" to fix)
        run: |
          terraform fmt -recursive
          git diff --exit-code
